### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by zmh2000829** [waylaidwanderer/PandoraAI#116]
**Describe the bug**
Encountered error when doing npm install
**To Reproduce**
1 git clone
2 npm install

**Expected behavior**
should complete install

**Screenshots**
![image](https://github.com/waylaidwanderer/PandoraAI/assets/44742019/3d69fdb3-2fe9-4990-9aae-bd233e916f6d)

![image](https://github.com/waylaidwanderer/PandoraAI/assets/44742019/e137bfce-e55e-4312-a47a-086aad766ad2)

**Desktop (please complete the following information):**
 -  OS: Ubuntu 20.04
 -  node: v18.16.0
 -  npm: v9.6.2
 -  node-gyp: v9.3.1

**Additional context**
also npm install sharp failed

**Comment by waylaidwanderer** [comment]
Have you run `apt install build-essential`?

**Comment by zmh2000829** [comment]
Thank you for your fast response, yes I did that but it doesn't help.

**Comment by hqw567** [comment]
> **Describe the bug** A clear and concise description of what the bug is. Encountered error when doing npm install **To Reproduce** Steps to reproduce the behavior: 1 git clone 2 npm install
> 
> **Expected behavior** should complete install
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/44742019/240186012-3d69fdb3-2fe9-4990-9aae-bd233e916f6d.png)
> 
> ![image](https://user-images.githubusercontent.com/44742019/240185459-e137bfce-e55e-4312-a47a-086aad766ad2.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 20.04
> * node: v18.16.0
> * npm: v9.6.2
> * node-gyp: v9.3.1
> 
> **Additional context** also npm install sharp failed

npm has restored the default source and reinstalled to resolve the issue

**Comment by waylaidwanderer** [comment]
I don't think this is related to this repository and is more of an environment issue, so I will be closing this. You can try running the Dockerfile instead.
