### ISSUE TITLE
pnpm install error

### ISSUE THREAD

**Issue by hqw567** [waylaidwanderer/PandoraAI#119]
**Describe the bug**
Dependencies cannot be installed properly

**To Reproduce**
1. git clone https://github.com/waylaidwanderer/PandoraAI.git
2. cd PandoraAI
3. pnpm install 

**Screenshots**
![image](https://github.com/waylaidwanderer/PandoraAI/assets/74847198/18f34286-eca0-45b4-9bf3-bc1a5375bbdd)

**Desktop (please complete the following information):**
 - OS: Windows 11 22621.891
 - pnpm: v8.5.1
 - node: v18.16.0

**Comment by hqw567** [comment]
sharp Install failed , It should be China's GFW issue，

https://github.com/lovell/sharp/issues/3682

**Comment by hqw567** [comment]
npm has restored the default source and reinstalled to resolve the issue

**Comment by tobychidi** [comment]
See I have this problem now. Why is that?

**Comment by tobychidi** [comment]
> npm has restored the default source and reinstalled to resolve the issue

I don't understand this solution
