### ISSUE TITLE
Why is the response the webpage content?

### ISSUE THREAD

**Issue by Maddaxman** [waylaidwanderer/PandoraAI#124]
![IMG_1467](https://github.com/waylaidwanderer/PandoraAI/assets/31379908/1067b3e4-a5dc-4486-9f8e-b46f27d5b79f)
ISSUES REPORTED HERE SHOULD BE FOR THE FRONT-END CLIENT ONLY.
Do NOT create issues regarding any websites that use this client, e.g. https://example-pandora-ai.app. Instead, please contact the website owner directly. 
If you are having problems related to node-chatgpt-api, open an issue there instead.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by waylaidwanderer** [comment]
Looks like your IP is blocked by Bing or your cookies are not set correctly.

**Comment by Maddaxman** [comment]
> Looks like your IP is blocked by Bing or your cookies are not set correctly.

Previously, I was able to run the user token configuration on the API server. However, it stopped working these past two days. Then I tried configuring the complete cookie and it worked again.
