### ISSUE TITLE
Bing jailbreak not working anymore

### ISSUE THREAD

**Issue by idcbye** [waylaidwanderer/PandoraAI#154]
**Describe the bug**
<img width="305" alt="image" src="https://github.com/waylaidwanderer/PandoraAI/assets/96666335/2052d4bf-c601-49ae-adba-b8a32a587138">
This happens with jailbreak creative precise etc.

**To Reproduce**
1. Go to Bing chat
2. Click on creative or precise with jailbreak on
3. Ask it an immoral question
4. It nukes its message halfway through

**Screenshots**
https://github.com/waylaidwanderer/PandoraAI/assets/96666335/5e447fee-8b40-4b8a-8e50-d51e6e63e90d

**Comment by Richard-Weiss** [comment]
Sorry for the late reply, but you can also look at [this issue](https://github.com/waylaidwanderer/node-chatgpt-api/issues/456) for a fix.

**Comment by Richard-Weiss** [comment]
Should be fixed in [PR](https://github.com/waylaidwanderer/node-chatgpt-api/pull/457) in [node-chatgpt-api](https://github.com/waylaidwanderer/node-chatgpt-api).

**Comment by waylaidwanderer** [comment]
Fixed in [1.37.3](https://www.npmjs.com/package/@waylaidwanderer/chatgpt-api/v/1.37.3)
