### ISSUE TITLE
It can't run successfully in my ipad.

### ISSUE THREAD

**Issue by MouJieQin** [waylaidwanderer/PandoraAI#17]
I can communicate with ChatGpt normally in my Mac. like this,
![image](https://user-images.githubusercontent.com/29160027/225649896-1b8b9f2a-81f1-467a-a9a7-ba2a71387659.png)
But I can't get response from AI in my iPad or iphone.  No matter how many time I try, it's always like this,
![image](https://user-images.githubusercontent.com/29160027/225650610-ee7888f2-51e5-4ba2-bab2-a3e26a4a0078.png)

**Comment by waylaidwanderer** [comment]
I'm guessing your node-chatgpt-api server is running on your Mac? Your iPad won't be able to connect to it in that case, since the address is set to `localhost:3000` by default.
