### ISSUE TITLE
Server / client question

### ISSUE THREAD

**Issue by AVTPJ** [waylaidwanderer/PandoraAI#18]
Could you explain a little about how the deployment works?

Am I right that you need both the `node-chatgpt-api` and PandoraAI running? Could I package the server and Pandora into one build for server(/serverless) deployment?

Should PandoraAI be able to run when generating a package for static hosting?

Great projects!

**Comment by waylaidwanderer** [comment]
Thanks for the kind words!

Yes, you need both projects running. With PandoraAI, you can run `npm run build`, which will generate a Node.js server you can run, or you can run `npm run generate`, which will generate static files you can upload to a host like Netlify or Vercel.

**Comment by AVTPJ** [comment]
Excellent, thanks!

**Comment by getxd-dev** [comment]
> Thanks for the kind words!
> 
> Yes, you need both projects running. With PandoraAI, you can run `npm run build`, which will generate a Node.js server you can run, or you can run `npm run generate`, which will generate static files you can upload to a host like Netlify or Vercel.
> 
> Keep in mind that both projects run on port 3000 by default, so if you want to run both on the same machine, it's probably a good idea to change the `node-chatgpt-api` server's port.

I both tried Netlify and Vercel and it seems that they are having trouble connect to the API server. I tried asking questions but it just doesn't work, are there any free alternatives?
