### ISSUE TITLE
Default Tone/Mode

### ISSUE THREAD

**Issue by getxd-dev** [waylaidwanderer/PandoraAI#24]
Is there a way to set a default tone to Bing? I want it to be in Creative mode automatically. Is there also a way to make jailbreak mode on by default?

**Comment by waylaidwanderer** [comment]
1.
![image](https://user-images.githubusercontent.com/2882110/226745017-7b41677a-4975-4dfc-afa6-4160c807f5a2.png)
2.
![image](https://user-images.githubusercontent.com/2882110/226745097-897cbe65-7e72-4a9f-91e4-b3584d0f1a7c.png)
3.
![image](https://user-images.githubusercontent.com/2882110/226745210-5a262eac-5cc0-4bc4-9645-85dee9454baa.png)
