### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by piwawa** [waylaidwanderer/PandoraAI#26]
![image](https://user-images.githubusercontent.com/46926496/226779769-85f10b4b-6203-49f2-bea2-32212f032f1e.png)
![image](https://user-images.githubusercontent.com/46926496/226779811-816cd008-cbff-4976-a732-13afae06f9b5.png)
I also don't know what the next step.

**Comment by waylaidwanderer** [comment]
Try updating to Node 18 at least, then delete `node_modules` folder and try again.
