### ISSUE TITLE
Is it possible to provide an API interface that can be used to create Telegram bots?

### ISSUE THREAD

**Issue by elliclee** [waylaidwanderer/PandoraAI#32]
Pandora AI's native responses are very interesting, especially with the use of emoji expressions. It would be even better if it can be deployed on Telegram/Discord to chat through a bot. I feel that Pandora AI's native responses have a significant difference compared to ChatGPT/Bing.

**Comment by waylaidwanderer** [comment]
PandoraAI is powered by `node-chatgpt-api`. In this case, it's using the jailbreak method applied to BingAIClient, which you can use yourself. Here's a demo of how:
https://github.com/waylaidwanderer/node-chatgpt-api/blob/main/demos/use-bing-client.js#L61-L103
