### ISSUE TITLE
ERROR Error: Failed to send message. Server closed the connection unexpectedly.

### ISSUE THREAD

**Issue by Bruce7988** [waylaidwanderer/PandoraAI#34]
ERROR Error: Failed to send message. Server closed the connection unexpectedly.
    onclose Chat.vue:333
    NuxtJS 3
    sendMessage Chat.vue:322
    async*_sfc_render/_cache[2]< NuxtJS
    withModifiers chunk-3NMN3MUW.js:9171
    withKeys chunk-3NMN3MUW.js:9190
    callWithErrorHandling chunk-3NMN3MUW.js:1580
    callWithAsyncErrorHandling chunk-3NMN3MUW.js:1588
    invoker chunk-3NMN3MUW.js:8198
    addEventListener chunk-3NMN3MUW.js:8153
    patchEvent chunk-3NMN3MUW.js:8167
    patchProp chunk-3NMN3MUW.js:8224
    mountElement chunk-3NMN3MUW.js:5786
    processElement chunk-3NMN3MUW.js:5764
    patch chunk-3NMN3MUW.js:5698
    mountChildren chunk-3NMN3MUW.js:5845
    mountElement chunk-3NMN3MUW.js:5777
    processElement chunk-3NMN3MUW.js:5764
    patch chunk-3NMN3MUW.js:5698
    mountChildren chunk-3NMN3MUW.js:5845
    mountElement chunk-3NMN3MUW.js:5777
    processElement chunk-3NMN3MUW.js:5764
    patch chunk-3NMN3MUW.js:5698
    mountChildren chunk-3NMN3MUW.js:5845
    mountElement chunk-3NMN3MUW.js:5777
    processElement chunk-3NMN3MUW.js:5764
    patch chunk-3NMN3MUW.js:5698
    mountChildren chunk-3NMN3MUW.js:5845
    processFragment chunk-3NMN3MUW.js:5978
    patch chunk-3NMN3MUW.js:5694
    componentUpdateFn chunk-3NMN3MUW.js:6128
    run chunk-3NMN3MUW.js:405
    update chunk-3NMN3MUW.js:6220
    setupRenderEffect chunk-3NMN3MUW.js:6228
    mountComponent chunk-3NMN3MUW.js:6046
    processComponent chunk-3NMN3MUW.js:6011
    patch chunk-3NMN3MUW.js:5700
    mountChildren chunk-3NMN3MUW.js:5845
    mountElement chunk-3NMN3MUW.js:5777
Chat.vue:361

![图片](https://user-images.githubusercontent.com/2604278/227768813-d4cfe1e8-10b1-4fae-8a24-73a5a37a4101.png)

**Comment by waylaidwanderer** [comment]
This is an issue with your `node-chatgpt-api` setup. Try doing a `GET /ping` request manually using cURL or Postman to see if you can connect to the API server.
