### ISSUE TITLE
Sorry, you are not allowed to access this service.

### ISSUE THREAD

**Issue by Frozen66** [waylaidwanderer/PandoraAI#35]
呜呜呜快帮忙看看呢

**Comment by lihongyang0929** [comment]
Same Issue but I'm wondering why.Is the goverment limited it or just the software updating temperally?

**Comment by nerorosa** [comment]
Sorry, you are not allowed to access this service.
same.....

**Comment by waylaidwanderer** [comment]
This is irrelevant to this repo, which is just a frontend client.

For more info, see: https://github.com/waylaidwanderer/node-chatgpt-api/issues?q=Sorry%2C+you+are+not+allowed+to+access+this+service
