### ISSUE TITLE
Is this website no longer maintained?

### ISSUE THREAD

**Issue by QingQiu2** [waylaidwanderer/PandoraAI#41]
No matter what I type, the site doesn't respond.
I have tried various devices since yesterday, but nothing is responding properly.
**To Reproduce**
Steps to reproduce the behaviour:

Just a simple conversation with PandoraAI

**Screenshots**
![Screenshot_2023-03-29-15-34-52-923_com.android.browser.jpg](https://user-images.githubusercontent.com/118521068/228461759-926777b2-5920-4829-80a9-e22315c0272f.jpg)

**Additional context**
When I used it yesterday, it showed：Sorry, you are not allowed to access this service.But today it doesn't respond to messages at all.So the website is not maintained?

**Comment by MARS-J** [comment]
I had the same problem

**Comment by MARS-J** [comment]
@QingQiu2 I had the same problem

**Comment by waylaidwanderer** [comment]
I don't host my client for public use, so please don't open issues that aren't related to bugs with the code.

I highly recommend you run your own instance of the client and API server.
