### ISSUE TITLE
开启服务后本机可以通过ip访问，同局域网下其他设备无法通过ip访问（端口已开放）

### ISSUE THREAD

**Issue by xiao-xi12** [waylaidwanderer/PandoraAI#42]
开启服务后本机可以通过ip访问，同局域网下其他设备无法通过ip访问（端口已开放）

**Comment by waylaidwanderer** [comment]
Not sure what this is but it doesn't seem like an issue with the frontend client.

**Comment by xiao-xi12** [comment]
> Not sure what this is but it doesn't seem like an issue with the frontend client.
Sorry, I found the problem, is about the inbound connections of Node.js in Firewall settings, thank you

**Comment by sizukamasou** [comment]
> 



> > 不确定这是什么，但它似乎不是前端客户端的问题。
> > 抱歉，我找到了问题，是关于防火墙设置中 Node.js 的入站连接，谢谢

node入站规则你是如何填写的？我发现我用端口映射到外面后，别人可以通过这个域名访问，但是bing却没办法回复
