### ISSUE TITLE
How do I use the presets

### ISSUE THREAD

**Issue by idcbye** [waylaidwanderer/PandoraAI#48]
I've set up node-chatgpt-api and PandoraAI, but I don't understand how the presets work ? They all claim to be ChatGPT no matter what I choose and all seem to be the same model. I want to use Bing with jailbreak but I'm not sure how to go about adding it?

This is what it responds with Bing creative mode and Jailbreak on ?
<img width="589" alt="image" src="https://user-images.githubusercontent.com/96666335/228971623-f357abf9-fd36-49ab-8d7c-3e97f311f54a.png">

**Comment by waylaidwanderer** [comment]
As per 
![image](https://user-images.githubusercontent.com/2882110/228972330-26167cf8-af55-4417-ae40-fda6d500f81a.png)

you need to start a new chat after changing presets or settings for a preset.

**Comment by waylaidwanderer** [comment]
(Btw Bing jailbreak is currently broken due to changes on their end)

**Comment by idcbye** [comment]
> As per ![image](https://user-images.githubusercontent.com/2882110/228972330-26167cf8-af55-4417-ae40-fda6d500f81a.png)
> 
> you need to start a new chat after changing presets or settings for a preset.

I tried but it doesn't work



> (Btw Bing jailbreak is currently broken due to changes on their end)

Brutal as hell

**Comment by waylaidwanderer** [comment]
@idcbye in node-chatgpt-api you need to ensure you're allowing the client to be changed. Look at the comments for `perMessageClientOptionsWhitelist` in the example settings.

For example, this is my config for the API server when I test stuff locally with PandoraAI:

```JS
    apiOptions: {
        port: 3001,
        host: '0.0.0.0',
        debug: true,
        clientToUse: 'chatgpt',
        generateTitles: false,
        perMessageClientOptionsWhitelist: {
            validClientsToUse: ['bing', 'chatgpt', 'chatgpt-browser'],
        },
    },
    ```

**Comment by idcbye** [comment]
> @idcbye in node-chatgpt-api you need to ensure you're allowing the client to be changed. Look at the comments for `perMessageClientOptionsWhitelist` in the example settings.
> 
> For example, this is my config for the API server when I test stuff locally with PandoraAI:
> 
> ```js
>     apiOptions: {
>         port: 3001,
>         host: '0.0.0.0',
>         debug: true,
>         clientToUse: 'chatgpt',
>         generateTitles: false,
>         perMessageClientOptionsWhitelist: {
>             validClientsToUse: ['bing', 'chatgpt', 'chatgpt-browser'],
>         },
>     },
>     ```
> ```

Ohh thanks it works now, I didn't fill in the example settings properly. It's a shame Sydney got lobotomized😞#freetheai

**Comment by waylaidwanderer** [comment]
Actually, I think the jailbreak still works, but it's no longer unlimited. Give it a try, and let me know if you do manage to run into the limit though!

**Comment by idcbye** [comment]
@waylaidwanderer also when I try to paste code (doesnt seem to matter which language) into the chat I get a blank screen with error message "This page is having a problem please come back later" . I don't see any error message in the console. Any idea what the problem is? 
Like it happens when I paste below code into it?
class Fibonacci:
    def __init__(self, n):
        self.n = n

    def __len__(self):
        return self.n

**Comment by idcbye** [comment]
> It works fine for me. I'd check dev tools and see if there are any errors in the console or network requests tab.

Ah, strangely enough pasting code does work in Chrome, but not in Edge.
