### ISSUE TITLE
Error: Could not load file

### ISSUE THREAD

**Issue by Sissidark** [waylaidwanderer/PandoraAI#50]
**Describe the bug**
cant load file

**Screenshots**
![image](https://user-images.githubusercontent.com/92515662/229260227-bc5fccdc-4444-4edc-80ea-ba6459733f36.png)

**error info**

Nuxi 3.3.2                                                                                                    09:47:30
Nuxt 3.3.2 with Nitro 2.3.2                                                                                   09:47:30
                                                                                                              09:47:31

i Using default Tailwind CSS file from runtime/tailwind.css                                  nuxt:tailwindcss 09:47:32
i Tailwind Viewer: http://localhost:3000/_tailwind/                                          nuxt:tailwindcss 09:47:33
√ PWA icons and splash screens generated in 1601 ms                                                           09:47:34
i Vite client warmed up in 6102ms                                                                             09:47:41

 ERROR  Error: Could not load file:///D:/Programing/nodejs/node_global/node_modules/@waylaidwanderer/PandoraAI/.nuxt/dist/server/client.manifest.mjs (imported by node_modules/nuxt/dist/core/runtime/nitro/renderer.js): ENOENT: no such file or directory, open 'D:\Programing\nodejs\node_global\node_modules\@waylaidwanderer\PandoraAI\file:\D:\Programing\nodejs\node_global\node_modules\@waylaidwanderer\PandoraAI\.nuxt\dist\server\client.manifest.mjs'

undefined

√ Nitro built in 2123 ms

**Comment by waylaidwanderer** [comment]
You may need to delete `node_modules` and run `npm install` again. Also, ensure you're on Node 18 for best results.

**Comment by Sissidark** [comment]
> You may need to delete `node_modules` and run `npm install` again. Also, ensure you're on Node 18 for best results.

Still not working, same error, I have installed node18.15 using nvm

![image](https://user-images.githubusercontent.com/92515662/229267976-5941aa8b-b073-4014-8248-1aeb29fd0b2a.png)
![image](https://user-images.githubusercontent.com/92515662/229267987-50fce64e-7efb-48ff-bb4c-95199ddc94c0.png)
![image](https://user-images.githubusercontent.com/92515662/229268014-545e17ec-1ab4-4ed5-98af-8e71b1aaf5de.png)
![image](https://user-images.githubusercontent.com/92515662/229268022-c3d4ae31-42d5-4949-817f-4c5bde7de5cc.png)

**Comment by Sissidark** [comment]
Is there a problem with the path? You can see that the path is repeated in the error message.
![image](https://user-images.githubusercontent.com/92515662/229268136-d7046bd0-55b5-42d2-a330-c07fa7eba180.png)

**Comment by waylaidwanderer** [comment]
I've never seen anything like that before. If it's a Nuxt issue perhaps you should open an issue on their repo?

**Comment by Sissidark** [comment]
> I've never seen anything like that before. If it's a Nuxt issue perhaps you should open an issue on their repo?

ok.anyway thanks for your help.
