### ISSUE TITLE
Copy Button in Code Block doesn't work

### ISSUE THREAD

**Issue by ha0min** [waylaidwanderer/PandoraAI#55]
**Describe**
I'm having trouble using the Copy Button feature in code blocks on PandoraAI. Whenever I try to click on it, nothing happens. I've tried this on multiple browsers and devices, but the issue persists.

**To Reproduce**
1. Navigate to any repository on GitHub that contains code blocks.
2. Click on the Copy Button in any code block.
3. Observe that nothing happens.
4. Console log error.

**Expected behavior**
Clicking on the Copy Button should copy the code from the code block to the clipboard.

**Screenshots**
Console log error as:
<img width="591" alt="image" src="https://user-images.githubusercontent.com/49261056/229663900-1f92432c-3358-47b1-a737-3515830fce81.png">
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLDocument.copyButtonListener

**Desktop:**
 - OS: MacOS
 - Browser: Edge
 - Version 111.0.1661.27 Dev(x86_64)

**Comment by waylaidwanderer** [comment]
See: https://stackoverflow.com/questions/71873824/copy-text-to-clipboard-cannot-read-properties-of-undefined-reading-writetext. Does it apply to you?

**Comment by ha0min** [comment]
Yes, I realized the server was deployed over HTTP instead of HTTPS, thanks!
