### ISSUE TITLE
Sorry, you are not allowed to access this service.

### ISSUE THREAD

**Issue by Geralt-Revived** [waylaidwanderer/PandoraAI#59]
**Describe the bug**
I am not allowed to access this service.

**To Reproduce**

**Expected behavior**

**Screenshots**
![impicture_20230408_132809](https://user-images.githubusercontent.com/54176179/230705155-2171df2f-5e99-4e7c-a55f-864d5bc6051b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by waylaidwanderer** [comment]
What's the value of the Bing cookies you set?

**Comment by Geralt-Revived** [comment]
I am not set Bing cookies this's null
![impicture_20230408_135001](https://user-images.githubusercontent.com/54176179/230705675-ab67bf30-c5c5-40d1-9fd0-10a5a4593c5b.png)
Should i need set Bing cookies to a suitable value?

**Comment by waylaidwanderer** [comment]
Yes.

**Comment by Geralt-Revived** [comment]
How i get the suitable value?

**Comment by cmp-nct** [comment]
Open Edge, go to Bing, go to bing chat, add yourself to the waitinglist, wait until activated, chat with the bot there, go to development mode (F12 on win) and find the cookies of the network request or get a cookie extension and copy it that way

**Comment by Geralt-Revived** [comment]
> Open Edge, go to Bing, go to bing chat, add yourself to the waitinglist, wait until activated, chat with the bot there, go to development mode (F12 on win) and find the cookies of the network request or get a cookie extension and copy it that way
> 
> That's the solution to the bug, it can be closed now :)

Thanks for your answer! but i wonder that must choose Bing preset?

![impicture_20230410_112645](https://user-images.githubusercontent.com/54176179/230819583-46bff705-334e-4e2e-a140-1cb29c3b9e96.png)
