### ISSUE TITLE
Stream display is not working.

### ISSUE THREAD

**Issue by owendswang** [waylaidwanderer/PandoraAI#60]
I'm using Bing bot, but stream display function is not working.
Is it client problem or the server side problem?

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: git master

**Comment by waylaidwanderer** [comment]
Can you share details about how you're hosting your node-chatgpt-api server?

**Comment by ztc1997** [comment]
Are you accessing the backend through a reverse proxy?

**Comment by owendswang** [comment]
> Are you accessing the backend through a reverse proxy?

Yes. Nginx 'proxy_pass'.

**Comment by owendswang** [comment]
OMG，it's nginx's problem.

After adding following settings to nginx proxy settings, it works then.
`proxy_http_version 1.1;
proxy_set_header Connection "";`
