### ISSUE TITLE
Can't modify port

### ISSUE THREAD

**Issue by nameless0412** [waylaidwanderer/PandoraAI#61]
**Describe the bug**

I modified the port in the setting file of the api, and modified the port in the env in the pandora project, and the port was not modified when I finally ran it.And open the given website with only one nuxt logo, and click it to enter the official website of nuxt, Is there something wrong with me?

**Expected behavior**
A clear and concise des

cription of what you expected to happen.

**Screenshots**
![18)%L XA9COBI83 XCTP9M](https://user-images.githubusercontent.com/130334747/230825646-789dc768-ae4a-4ca9-b343-e348496495f7.png)
![R`T8 )Q475B{ZCK$SR}D1{K](https://user-images.githubusercontent.com/130334747/230825655-75495ed6-0eb2-4f49-8ca6-b19925753693.png)
![YBPH68S QKT ~PN@F8}FAOT](https://user-images.githubusercontent.com/130334747/230825665-64bbc0c3-2a08-4d65-8784-c01cff4b5cb8.png)

**Comment by ayxj0** [comment]
Please describe your problem in more detail.The port in env is the port to connect to node-chatgpt-api, and the port of api can be set by yourself. The port of the website is fixed at 3000.Please visit your website address and give me a screenshot to let me know what problem you encountered.

**Comment by nameless0412** [comment]
Thank you, I have solved the problem now, I used to understand that if I changed the port of api and the website, the port of nuxt would be the same as them, it was my misunderstanding, it has been solved now, thank you again!!

**Comment by nameless0412** [comment]
Thank you, I have solved the problem now, I used to understand that if I changed the port of api and the website, the port of nuxt would be the same as them, it was my misunderstanding, it has been solved now, thank you again!!
