### ISSUE TITLE
BingAI does not connect

### ISSUE THREAD

**Issue by aplodismenty** [waylaidwanderer/PandoraAI#67]
Can't connect, although it has passed a couple of times
![Screenshot_6](https://user-images.githubusercontent.com/78805388/231174803-c7fc04c4-a2d8-4f2f-9f52-e2c94a27dabb.png)

**Comment by waylaidwanderer** [comment]
Ensure in your node-chatgpt-api config that you allow users to set their own cookies in `perMessageClientOptions`. Additionally, your cookie looks to be in the wrong format.

**Comment by aplodismenty** [comment]
![image](https://user-images.githubusercontent.com/78805388/232546333-d00eb59a-d3f3-41e2-bbfd-023795bc34cc.png)
tell me the correct cookie format.
