### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by LTDZ15** [waylaidwanderer/PandoraAI#68]
User
111

AI

Cannot convert argument to a ByteString because the character at index 406 has a value of 28009 which is greater than 255.

age. Server closed the connection unexpectedly.
    at onclose (Chat.vue:333:1)
    at create (fetch.ts:125:17)
sendMessage @ Chat.vue:361
await in sendMessage(异步)
_createElementBlock.onClick._cache.<computed>._cache.<computed> @ Chat.vue:515
callWithErrorHandling @ chunk-3NMN3MUW.js:1580
callWithAsyncErrorHandling @ chunk-3NMN3MUW.js:1588
invoker @ chunk-3NMN3MUW.js:8198
Show 3 more frames

**Comment by LTDZ15** [comment]
https://freeimage.host/i/HkD5DPt

**Comment by waylaidwanderer** [comment]
I think your cookie string has some non-latin characters in it causing the issue. Regardless, this isn't the correct repo for this issue.
