### ISSUE TITLE
After using internal network penetration, it is not working properly.

### ISSUE THREAD

**Issue by Passerby1011** [waylaidwanderer/PandoraAI#87]
ISSUES REPORTED HERE SHOULD BE FOR THE FRONT-END CLIENT ONLY.
Do NOT create issues regarding any websites that use this client, e.g. https://example-pandora-ai.app. Instead, please contact the website owner directly. 
If you are having problems related to node-chatgpt-api, open an issue there instead.

**Describe the bug**

**To Reproduce**

Hello, I have successfully deployed ChatGPT on my NAS, and I can have conversations with it within my local network. However, when I use frp to forward port 3000, the web page can still be accessed normally, but ChatGPT does not respond to queries.
Also, I hope to improve the response speed. The current response speed is a bit slow compared to other projects of the same type.

**Expected behavior**

**Screenshots**
![Screenshot_20230417_234222_com yandex browser alpha](https://user-images.githubusercontent.com/63802758/232539191-4ee1f9a8-4acf-41b0-b566-30119753b3c2.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sizukamasou** [comment]
你成功部署了吗？我使用ddns的内网穿透功能，能够通过域名打开网页，但是bing没办法和我交互对话

**Comment by Passerby1011** [comment]
成功了，后端地址映射出来，前端直接填那个映射的地址
